### PR TITLE
Expose getWorkingPath

### LINKED ISSUE #32: Is there any way to detect which route has matched?
I have conditional rendering case like
```js
props => {
let match = useRouter({
'/sign-in': () => <SignInScreen/>,
'/dashboard': () => <DashboardScreen/>
})

return <main>
{isSignInScreen && <NavBar/>}
{match || <>Not Fount</>}
</main>
}
```

What's the best way to detect `isSignInScreen` flag?

### PR DESCRIPTION
**Pull request by dy**
Fixes #32

### CODE REVIEW

**Comment by Paratron** [comment]
Thanks for the work, I will consider this for future releases. Altough, documentation needs to be written and tests need to be created if the function delivers a reliable value for outside applications to use.

Since I - for now - don't really see a value gain for the router library that justifies the additional work, I will leave the PR open but mark it as probably won't fix.

**Comment by dy** [comment]
The most apparent use-case is displaying active link in navigation.
```js
menuItems.map(item => {
            let active = getWorkingPath() === item.href

            return (
                <A href={item.href} style={{ color: active ? 'blue' : 'black'}}>
                  { item.label }
                </A>
            )
```
What's the workaround without that function?

The second use-case is, as mentioned, conditional rendering chunks of the page. Without that function there is too much boilerplate code.

```js
let Page = useRouter(routes)
let path = getWorkingPath()

return [
path !== `/sign-in` ? <Navbar /> : null,
Page
]
```
_react-router_ passes `location.pathname` prop for that purpose.

**Comment by dy** [comment]
Ok, added description to the docs.
That's pretty ridiculous I have to sell that _standard_ use-case.
There is no test for _getPath_ or _setPath_, so I skipped test.
History navigation still does not work, almost sure that's the library issue, the usage in the app is standard. 
Just close the PR instead of letting it hang if you consider that useless.

**Comment by Paratron** [comment]
Thanks again for your work!
I think I will turn that into a hook that should work both on SSR as well as on frontend.

**Pull request merged**
